### ISSUE TITLE
Button text not restored properly if it was changed

### ISSUE THREAD

**Issue by rammara** [stefanocudini/bootstrap-confirm-button#5]
If the button text is changed after the constructor is called the button text will not be properly restored.
(origHtml is read once and is not checked whether it was changed afterwards)

Example here: https://www.bootply.com/B44OLwBTmU

**Comment by stefanocudini** [comment]
this plugin can not know if the text from other libraries is changed

**Comment by rammara** [comment]
Oh, ok, but you only need to re-check the button text before actually invoking.
Instead of:
```
    var opts = $.extend({
        msg: "I'm sure!",
        classname: 'btn-danger',
        timeout: 2000
    }, opts);

```
I changed to:
 ```
   opts = $.extend({
        msg: "I'm sure!",
        classname: 'btn-danger',
        timeout: 2000
    }, opts);
```


That's all it took (just removed var in the beginning)

**Comment by stefanocudini** [comment]
then ok
